# Generated by Django 2.2.3 on 2019-08-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.TextField(default='unknown', max_length=255),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
